name: Pipe Pagamentos

on:
  workflow_dispatch: # execução manual
  push: # execução automática em push na main
    branches:
      - main 
  pull_request: # execução automática em PRs para main, incluido para testar no github antes de fazer o merge para a main
    branches:
      - main 
  schedule: # execução agendada
    #1° agendamento - Roda as Quintas e Sextas a cada 15 minutos
    - cron: '*/15 * * * 4,5'
    #2° agendamento - Roda aos sábados e domingos a cada hora    
    - cron: '0 * * * 0,6'        

# Forçar para não exibir mais alerta do gitHub no final da execução    
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    # runs-on: self-hosted # usar o runner próprio

    strategy:
      matrix:
        node-version: [ 23.x ] # versão do Node que vou testar
        #node-version: 'latest' #--- aqui para quando quiser usar a versão mais recente do node

    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # cache de dependências (npm)
      - name: Cache de dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # instalar dependências
      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com mochawesome
        run: npm test

      - name: Consolidar relatórios JSON
        if: ${{ always() }}
        run: npx mochawesome-merge mochawesome-report/*.json > mochawesome-report/merged.json

      - name: Gerar relatório HTML consolidado
        if: ${{ always() }}
        run: npx marge mochawesome-report/merged.json --reportDir mochawesome-report --reportFilename index  

      - name: Upload do relatório de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./mochawesome-report
          name: Relatório de Testes Mocha
          
      - name: Adicionar resumo no GitHub Actions
        if: ${{ always() }}
        run: |
          passed=$(jq '.stats.passes' mochawesome-report/merged.json)
          failed=$(jq '.stats.failures' mochawesome-report/merged.json)
          total=$(jq '.stats.tests' mochawesome-report/merged.json)

          echo "## 🧪 Resumo dos Testes" >> $GITHUB_STEP_SUMMARY
          echo "- Total de testes: $total" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Passaram: $passed" >> $GITHUB_STEP_SUMMARY
          echo "- ❌ Falharam: $failed" >> $GITHUB_STEP_SUMMARY
          echo "- 📂 Relatório/Artefato está disponível como: **Relatório de Testes de Pagamento**" >> $GITHUB_STEP_SUMMARY
