name: Node.js CI

on:
  workflow_dispatch: # execução manual
  push:
    branches:
      - main # execução automática em push na main
  pull_request:
    branches:
      - main # execução automática em PRs para main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    # runs-on: self-hosted # usar o runner próprio

    strategy:
      matrix:
        node-version: [23.x] # versões do Node que você quer testar

    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # cache de dependências (npm)
      - name: Cache de dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # instalar dependências
      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com mochawesome
        run: npm test

      - name: Upload do relatório de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./mochawesome-report
          name: Relatório de Testes Mocha
